#
#Wed Oct 18 11:37:47 EDT 2023
model.directory=/Users/me597/Documents/GitHub/gonorrheaABM/SimpleSIRgit
host.0.type=LOCAL
batch.param.file=/Users/me597/Documents/GitHub/gonorrheaABM/SimpleSIRgit/batch/batch_params.xml
poll.frequency=5.0
scenario.directory=/Users/me597/Documents/GitHub/gonorrheaABM/SimpleSIRgit/SimpleSIR.rs
param.file=/Users/me597/Documents/GitHub/gonorrheaABM/SimpleSIRgit/SimpleSIR.rs/parameters.xml
key.directory=/Users/ME597/.ssh
host.0.instances=2
output.directory=/Users/me597/Documents/GitHub/gonorrheaABM/SimpleSIRgit/output
vm.arguments=-XX\:+IgnoreUnrecognizedVMOptions --add-modules\=ALL-SYSTEM --add-exports\=java.base/jdk.internal.ref\=ALL-UNNAMED --add-exports\=java.base/java.lang\=ALL-UNNAMED --add-exports\=java.desktop/sun.awt\=ALL-UNNAMED --add-exports\=java.desktop/sun.java2d\=ALL-UNNAMED --add-opens\=java.base/java.lang\=ALL-UNNAMED --add-opens\=java.base/java.util\=ALL-UNNAMED -Xms8g -Xmx8g -Dfile.encoding\=UTF-8 -XX\:+ShowCodeDetailsInExceptionMessages
